/*
 *  This file is part of MONGKIE. Visit <http://www.mongkie.org/> for details.
 *  Copyright (C) 2012 Korean Bioinformation Center(KOBIC)
 * 
 *  MONGKIE is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  MONGKE is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 * 
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.mongkie.ui.datatable.graph;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;

/**
 *
 * @author Yeongjun Jang <yjjang@kribb.re.kr>
 */
public class ToolsPanel extends javax.swing.JPanel {

    /** Creates new form ToolsPanel */
    public ToolsPanel() {
        initComponents();
    }
    
    public List<JComponent> getToolComponents() {
        List<JComponent> tools = new ArrayList<JComponent>();
        for (Component c : jToolBar1.getComponents()) {
            tools.add((JComponent) c);
        }
        return tools;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mongkie/ui/datatable/resources/plus-circle.png"))); // NOI18N
        jButton1.setText(org.openide.util.NbBundle.getMessage(ToolsPanel.class, "ToolsPanel.jButton1.text")); // NOI18N
        jButton1.setFocusable(false);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mongkie/ui/datatable/resources/minus-circle.png"))); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(ToolsPanel.class, "ToolsPanel.jButton2.text")); // NOI18N
        jButton2.setFocusable(false);
        jToolBar1.add(jButton2);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mongkie/ui/datatable/resources/table-insert-column.png"))); // NOI18N
        jButton6.setText(org.openide.util.NbBundle.getMessage(ToolsPanel.class, "ToolsPanel.jButton6.text")); // NOI18N
        jButton6.setFocusable(false);
        jToolBar1.add(jButton6);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mongkie/ui/datatable/resources/table-delete-column.png"))); // NOI18N
        jButton4.setText(org.openide.util.NbBundle.getMessage(ToolsPanel.class, "ToolsPanel.jButton4.text")); // NOI18N
        jButton4.setFocusable(false);
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mongkie/ui/datatable/resources/disk-return.png"))); // NOI18N
        jButton5.setText(org.openide.util.NbBundle.getMessage(ToolsPanel.class, "ToolsPanel.jButton5.text")); // NOI18N
        jButton5.setFocusable(false);
        jToolBar1.add(jButton5);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mongkie/ui/datatable/resources/binocular--pencil.png"))); // NOI18N
        jButton3.setText(org.openide.util.NbBundle.getMessage(ToolsPanel.class, "ToolsPanel.jButton3.text")); // NOI18N
        jButton3.setFocusable(false);
        jToolBar1.add(jButton3);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/mongkie/ui/datatable/resources/funnel.png"))); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(ToolsPanel.class, "ToolsPanel.jLabel1.text")); // NOI18N
        jToolBar1.add(jLabel1);

        jTextField1.setText(org.openide.util.NbBundle.getMessage(ToolsPanel.class, "ToolsPanel.jTextField1.text")); // NOI18N
        jTextField1.setPreferredSize(new java.awt.Dimension(100, 26));
        jToolBar1.add(jTextField1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Symbol" }));
        jToolBar1.add(jComboBox1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
