/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProcessPanel.java
 *
 * Created on Apr 12, 2011, 7:33:29 PM
 */
package org.mongkie.ui.pipeline;

/**
 *
 * @author yjjang
 */
public class ProcessPanel extends javax.swing.JPanel {

    private String title;

    /** Creates new form ProcessPanel */
    public ProcessPanel(String title) {
        this.title = title;
        initComponents();
    }

    public String getTitle() {
        return title;
    }

    public void addPipelineAction(PipelineAction a) {
        add(a.getButton(), "wrap");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 15, 15));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
