//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.25 at 05:11:47 PM KST 
//


package org.mongkie.mimi.jaxb.official;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}InteractionID"/>
 *         &lt;element ref="{}GeneID"/>
 *         &lt;element ref="{}GeneSymbol"/>
 *         &lt;element ref="{}TaxonomyID"/>
 *         &lt;element ref="{}InteractionAttribute" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interactionID",
    "geneID",
    "geneSymbol",
    "taxonomyID",
    "interactionAttribute"
})
@XmlRootElement(name = "InteractingGene")
public class InteractingGene {

    @XmlElement(name = "InteractionID")
    protected int interactionID;
    @XmlElement(name = "GeneID", required = true)
    protected GeneID geneID;
    @XmlElement(name = "GeneSymbol", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String geneSymbol;
    @XmlElement(name = "TaxonomyID")
    protected int taxonomyID;
    @XmlElement(name = "InteractionAttribute", required = true)
    protected List<InteractionAttribute> interactionAttribute;

    /**
     * Gets the value of the interactionID property.
     * 
     */
    public int getInteractionID() {
        return interactionID;
    }

    /**
     * Sets the value of the interactionID property.
     * 
     */
    public void setInteractionID(int value) {
        this.interactionID = value;
    }

    /**
     * Gets the value of the geneID property.
     * 
     * @return
     *     possible object is
     *     {@link GeneID }
     *     
     */
    public GeneID getGeneID() {
        return geneID;
    }

    /**
     * Sets the value of the geneID property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneID }
     *     
     */
    public void setGeneID(GeneID value) {
        this.geneID = value;
    }

    /**
     * Gets the value of the geneSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneSymbol() {
        return geneSymbol;
    }

    /**
     * Sets the value of the geneSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneSymbol(String value) {
        this.geneSymbol = value;
    }

    /**
     * Gets the value of the taxonomyID property.
     * 
     */
    public int getTaxonomyID() {
        return taxonomyID;
    }

    /**
     * Sets the value of the taxonomyID property.
     * 
     */
    public void setTaxonomyID(int value) {
        this.taxonomyID = value;
    }

    /**
     * Gets the value of the interactionAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interactionAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInteractionAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InteractionAttribute }
     * 
     * 
     */
    public List<InteractionAttribute> getInteractionAttribute() {
        if (interactionAttribute == null) {
            interactionAttribute = new ArrayList<InteractionAttribute>();
        }
        return this.interactionAttribute;
    }

}
