//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.25 at 05:11:47 PM KST 
//


package org.mongkie.mimi.jaxb.official;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.mongkie.mimi.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Year_QNAME = new QName("", "Year");
    private final static QName _GeneSymbol_QNAME = new QName("", "GeneSymbol");
    private final static QName _InteractionID_QNAME = new QName("", "InteractionID");
    private final static QName _Details_QNAME = new QName("", "Details");
    private final static QName _Statement_QNAME = new QName("", "Statement");
    private final static QName _TaxonomyID_QNAME = new QName("", "TaxonomyID");
    private final static QName _GrantNumber_QNAME = new QName("", "GrantNumber");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.mongkie.mimi.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link InteractingGene }
     * 
     */
    public InteractingGene createInteractingGene() {
        return new InteractingGene();
    }

    /**
     * Create an instance of {@link GeneID }
     * 
     */
    public GeneID createGeneID() {
        return new GeneID();
    }

    /**
     * Create an instance of {@link InteractionAttribute }
     * 
     */
    public InteractionAttribute createInteractionAttribute() {
        return new InteractionAttribute();
    }

    /**
     * Create an instance of {@link NCIBI }
     * 
     */
    public NCIBI createNCIBI() {
        return new NCIBI();
    }

    /**
     * Create an instance of {@link MiMI }
     * 
     */
    public MiMI createMiMI() {
        return new MiMI();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link ParameterSet }
     * 
     */
    public ParameterSet createParameterSet() {
        return new ParameterSet();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Copyright }
     * 
     */
    public Copyright createCopyright() {
        return new Copyright();
    }

    /**
     * Create an instance of {@link Support }
     * 
     */
    public Support createSupport() {
        return new Support();
    }

    /**
     * Create an instance of {@link ResultSet }
     * 
     */
    public ResultSet createResultSet() {
        return new ResultSet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Year")
    public JAXBElement<BigInteger> createYear(BigInteger value) {
        return new JAXBElement<BigInteger>(_Year_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GeneSymbol")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGeneSymbol(String value) {
        return new JAXBElement<String>(_GeneSymbol_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InteractionID")
    public JAXBElement<Integer> createInteractionID(Integer value) {
        return new JAXBElement<Integer>(_InteractionID_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Details")
    public JAXBElement<String> createDetails(String value) {
        return new JAXBElement<String>(_Details_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Statement")
    public JAXBElement<String> createStatement(String value) {
        return new JAXBElement<String>(_Statement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TaxonomyID")
    public JAXBElement<Integer> createTaxonomyID(Integer value) {
        return new JAXBElement<Integer>(_TaxonomyID_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GrantNumber")
    public JAXBElement<String> createGrantNumber(String value) {
        return new JAXBElement<String>(_GrantNumber_QNAME, String.class, null, value);
    }

}
