//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.30 at 10:00:46 PM KST 
//


package org.mongkie.mimi.jaxb.annotation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}GeneType"/>
 *         &lt;element ref="{}GeneDescription"/>
 *         &lt;element ref="{}Organism"/>
 *         &lt;element ref="{}TaxonomyID"/>
 *         &lt;element ref="{}GeneSymbol"/>
 *         &lt;element ref="{}GeneID"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SourceKey" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "geneType",
    "geneDescription",
    "organism",
    "taxonomyID",
    "geneSymbol",
    "geneID"
})
@XmlRootElement(name = "Annotation")
public class Annotation {

    @XmlElement(name = "GeneType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String geneType;
    @XmlElement(name = "GeneDescription", required = true)
    protected String geneDescription;
    @XmlElement(name = "Organism", required = true)
    protected String organism;
    @XmlElement(name = "TaxonomyID")
    protected int taxonomyID;
    @XmlElement(name = "GeneSymbol", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String geneSymbol;
    @XmlElement(name = "GeneID")
    protected int geneID;
    @XmlAttribute(name = "SourceKey", required = true)
    protected int sourceKey;

    /**
     * Gets the value of the geneType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneType() {
        return geneType;
    }

    /**
     * Sets the value of the geneType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneType(String value) {
        this.geneType = value;
    }

    /**
     * Gets the value of the geneDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneDescription() {
        return geneDescription;
    }

    /**
     * Sets the value of the geneDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneDescription(String value) {
        this.geneDescription = value;
    }

    /**
     * Gets the value of the organism property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganism() {
        return organism;
    }

    /**
     * Sets the value of the organism property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganism(String value) {
        this.organism = value;
    }

    /**
     * Gets the value of the taxonomyID property.
     * 
     */
    public int getTaxonomyID() {
        return taxonomyID;
    }

    /**
     * Sets the value of the taxonomyID property.
     * 
     */
    public void setTaxonomyID(int value) {
        this.taxonomyID = value;
    }

    /**
     * Gets the value of the geneSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneSymbol() {
        return geneSymbol;
    }

    /**
     * Sets the value of the geneSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneSymbol(String value) {
        this.geneSymbol = value;
    }

    /**
     * Gets the value of the geneID property.
     * 
     */
    public int getGeneID() {
        return geneID;
    }

    /**
     * Sets the value of the geneID property.
     * 
     */
    public void setGeneID(int value) {
        this.geneID = value;
    }

    /**
     * Gets the value of the sourceKey property.
     * 
     */
    public int getSourceKey() {
        return sourceKey;
    }

    /**
     * Sets the value of the sourceKey property.
     * 
     */
    public void setSourceKey(int value) {
        this.sourceKey = value;
    }

}
